name: Ejemplo con Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Ejecutar contenedor Docker
        run: |
          docker run --rm hello-world
