name: Ejemplo básico

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Imprimir mensaje
        run: echo "Hola, Act!"


