name: Search Secrets
on:
  workflow_dispatch:
jobs:
  search-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Search Secrets
        id: search
        run: |
          org=${{ github.repository_owner }}
          repos=$(curl -s "https://api.github.com/orgs/$org/repos?per_page=100" | jq -r '.[] | .name')
          declare -A secretEnvironments
          declare -A repoEnvironments
          searchValue="acceskey"
          for repo in $repos; do
            secrets=$(curl -s "https://api.github.com/repos/$org/$repo/actions/secrets" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.secrets[]')
            for secret in $secrets; do
              secretName=$(echo "$secret" | jq -r '.name')
              secretValue=$(curl -s "https://api.github.com/repos/$org/$repo/actions/secrets/$secretName" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq -r '.value')
              if [[ $secretValue == *"$searchValue"* ]]; then
                environments=$(echo "$secret" | jq -r '.environments[]')
                for environment in $environments; do
                  if [[ -z "${secretEnvironments[$secretName]}" ]]; then
                    secretEnvironments[$secretName]="$environment"
                  else
                    secretEnvironments[$secretName]+=",$environment"
                  fi
                  if [[ -z "${repoEnvironments[$repo]}" ]]; then
                    repoEnvironments[$repo]="$environment"
                  else
                    repoEnvironments[$repo]+=",$environment"
                  fi
                done
              fi
            done
          done

